export default function DisclaimerPage() {
  return (
    <section className="py-12 px-6">
      <div className="max-w-2xl mx-auto">

        {/* Header */}
        <h1 className="text-2xl font-semibold text-stone-800 mb-1">Disclaimer</h1>
        <p className="text-xs text-stone-400 mb-10">Last updated: 1 March 2026</p>

        {/* 1. Informational Purpose */}
        <div className="mb-10">
          <h2 className="text-base font-semibold text-stone-700 mb-3 pb-1 border-b border-stone-200">
            1. Informational Purpose Only
          </h2>
          <p className="text-sm leading-relaxed text-stone-600 mb-3">
            All content, readings, and results on Where Sky Aligns — including alignment scores,
            Moon sign descriptions, compatibility readings, and zodiac reference material — are
            provided for informational purposes only.
          </p>
          <p className="text-sm leading-relaxed text-stone-600">
            Nothing on this Site is intended to inform, guide, or influence any significant
            life decision. The content should be treated as one interpretive perspective among
            many, not as a definitive statement about any person or situation.
          </p>
        </div>

        {/* 2. No Predictive Guarantees */}
        <div className="mb-10">
          <h2 className="text-base font-semibold text-stone-700 mb-3 pb-1 border-b border-stone-200">
            2. No Predictive Guarantees
          </h2>
          <p className="text-sm leading-relaxed text-stone-600 mb-3">
            Astrology is an interpretive system. Outputs generated by this Site are based on
            symbolic frameworks and the birth details you provide. They do not predict future
            events, guarantee outcomes, or provide certainty about any aspect of your life.
          </p>
          <p className="text-sm leading-relaxed text-stone-600">
            Alignment scores and compatibility readings reflect structural patterns within an
            astrological system. They are not assessments of a person&apos;s worth, potential,
            or future.
          </p>
        </div>

        {/* 3. Not Professional Advice */}
        <div className="mb-10">
          <h2 className="text-base font-semibold text-stone-700 mb-3 pb-1 border-b border-stone-200">
            3. Not a Substitute for Professional Advice
          </h2>
          <p className="text-sm leading-relaxed text-stone-600 mb-3">
            Content on this Site does not constitute — and should not be treated as — medical,
            psychological, financial, legal, or relationship advice.
          </p>
          <p className="text-sm leading-relaxed text-stone-600">
            If you are seeking guidance on health, wellbeing, finances, relationships, or any
            other significant matter, please consult a qualified professional. Where Sky Aligns
            is not a licensed advisory service of any kind.
          </p>
        </div>

        {/* 4. Personal Responsibility */}
        <div className="mb-10">
          <h2 className="text-base font-semibold text-stone-700 mb-3 pb-1 border-b border-stone-200">
            4. Personal Responsibility
          </h2>
          <p className="text-sm leading-relaxed text-stone-600 mb-3">
            By using this Site, you acknowledge that you are responsible for how you interpret
            and act on any content or results you receive. Where Sky Aligns does not accept
            responsibility for choices made in response to content on this Site.
          </p>
          <p className="text-sm leading-relaxed text-stone-600">
            We encourage a reflective, considered approach to astrological content — treating
            it as one lens among many rather than a fixed truth.
          </p>
        </div>



      </div>
    </section>
  )
}
